
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nabil Newaz
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LastReading = new javax.swing.JTextField();
        LastDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        CurrentReading = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CurrentDateChooser = new com.toedter.calendar.JDateChooser();
        CalculateButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CalculatedDataShow = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        NetEcectricBill = new javax.swing.JLabel();
        TotalUnitShow = new javax.swing.JLabel();
        UseTimes = new javax.swing.JLabel();
        DemandChargeShow = new javax.swing.JLabel();
        ServiceChargeShow = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        VatAmmountShow = new javax.swing.JLabel();
        PrincipalAmmountShow = new javax.swing.JLabel();
        TotalBillShow = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        WrongInput = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill Calculator BD");
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Nabil Newaz\\Documents\\NetBeansProjects\\BillCalculatorBD\\image\\TitelImage.png"));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(43, 174, 102));

        jLabel1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://raw.githubusercontent.com/NabilNewaz/BillCalculatorBD/master/image/InUiImage.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill Calculator BD");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Calculate Your Electric Bill");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("INPUT YOUR METER DATA");

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Last Meter Reading");

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));

        LastReading.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LastReading.setForeground(new java.awt.Color(153, 153, 153));
        LastReading.setText("Enter Reading");
        LastReading.setBorder(null);
        LastReading.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastReadingMouseClicked(evt);
            }
        });
        LastReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastReadingActionPerformed(evt);
            }
        });

        LastDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        LastDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        LastDateChooser.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        LastDateChooser.setMaxSelectableDate(new java.util.Date(253370746871000L));
        LastDateChooser.setMinSelectableDate(new java.util.Date(-62135787529000L));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Last Reading Date");

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));

        CurrentReading.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CurrentReading.setForeground(new java.awt.Color(153, 153, 153));
        CurrentReading.setText("Enter Reading");
        CurrentReading.setBorder(null);
        CurrentReading.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurrentReadingMouseClicked(evt);
            }
        });
        CurrentReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentReadingActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Current Reading");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Current Date");

        CurrentDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        CurrentDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        CurrentDateChooser.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N

        CalculateButton.setBackground(new java.awt.Color(43, 174, 102));
        CalculateButton.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(255, 255, 255));
        CalculateButton.setText("Calculate Bill");
        CalculateButton.setToolTipText("");
        CalculateButton.setBorder(null);
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(43, 174, 102));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CalculatedDataShow.setBackground(new java.awt.Color(255, 255, 255));
        CalculatedDataShow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 174, 102)));
        CalculatedDataShow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Usage Unit");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Net Electric Bill");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Demand Charge");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Service Charge");

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Principal Ammount");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Vat");

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Total Bill");

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Usage Time");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText(":");

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText(":");

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText(":");

        jLabel23.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText(":");

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText(":");

        NetEcectricBill.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        NetEcectricBill.setForeground(new java.awt.Color(51, 51, 51));

        TotalUnitShow.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        TotalUnitShow.setForeground(new java.awt.Color(51, 51, 51));

        UseTimes.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        UseTimes.setForeground(new java.awt.Color(51, 51, 51));

        DemandChargeShow.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        DemandChargeShow.setForeground(new java.awt.Color(51, 51, 51));

        ServiceChargeShow.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        ServiceChargeShow.setForeground(new java.awt.Color(51, 51, 51));

        jLabel30.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));

        VatAmmountShow.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        VatAmmountShow.setForeground(new java.awt.Color(51, 51, 51));

        PrincipalAmmountShow.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        PrincipalAmmountShow.setForeground(new java.awt.Color(51, 51, 51));

        TotalBillShow.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        TotalBillShow.setForeground(new java.awt.Color(51, 51, 51));

        jLabel34.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));

        jLabel35.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout CalculatedDataShowLayout = new javax.swing.GroupLayout(CalculatedDataShow);
        CalculatedDataShow.setLayout(CalculatedDataShowLayout);
        CalculatedDataShowLayout.setHorizontalGroup(
            CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalBillShow, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                        .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16))
                        .addGap(23, 23, 23)
                        .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NetEcectricBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalUnitShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UseTimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DemandChargeShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ServiceChargeShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                        .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VatAmmountShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrincipalAmmountShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        CalculatedDataShowLayout.setVerticalGroup(
            CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel23))
                    .addComponent(UseTimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel22))
                    .addComponent(TotalUnitShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel21))
                    .addComponent(NetEcectricBill, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel20))
                    .addComponent(DemandChargeShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel19))
                    .addComponent(ServiceChargeShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel17))
                    .addComponent(PrincipalAmmountShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel18))
                    .addComponent(VatAmmountShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                        .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel24))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TotalBillShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addGap(86, 86, 86)))
            .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addGap(32, 32, 32)))
            .addGroup(CalculatedDataShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CalculatedDataShowLayout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
        );

        WrongInput.setBackground(new java.awt.Color(255, 255, 255));
        WrongInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 174, 102)));
        WrongInput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel42.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Please Check Input Data");

        javax.swing.GroupLayout WrongInputLayout = new javax.swing.GroupLayout(WrongInput);
        WrongInput.setLayout(WrongInputLayout);
        WrongInputLayout.setHorizontalGroup(
            WrongInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WrongInputLayout.setVerticalGroup(
            WrongInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LastReading, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LastDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(CurrentReading, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CurrentDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(CalculatedDataShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WrongInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LastReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LastDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CurrentReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CurrentDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(WrongInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalculatedDataShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastReadingActionPerformed
        // TODO add your handling code here:
        //String PrevReadiing = LastReading.getText();
    }//GEN-LAST:event_LastReadingActionPerformed

    private void CurrentReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentReadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentReadingActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        // TODO add your handling code here:
        
        //Get Input Metar Reading
        String PrevReading = LastReading.getText();
        String NewReading = CurrentReading.getText();
        double Old = Double.parseDouble(PrevReading);
        double New = Double.parseDouble(NewReading);
        double TotalUnit = (New-Old);
        String TotalUnitOut = String.valueOf(new DecimalFormat("##.##").format(TotalUnit));
        
        //Get Date Input
        SimpleDateFormat DF = new SimpleDateFormat ("dd MM yyyy");
        String LastDate = DF.format(LastDateChooser.getDate());
        String CurrentDate = DF.format(CurrentDateChooser.getDate());
        
        //Calculate Usage Time
        int UseTime = 0;
        try {
            Date dateBefore = DF.parse(LastDate);
            Date dateAfter = DF.parse(CurrentDate);
            long difference = dateAfter.getTime() - dateBefore.getTime();
            float daysBetween = (difference / (1000*60*60*24));
            UseTime = (int) daysBetween + 1;
            String UsageTime = String.valueOf(UseTime);
            UseTimes.setText(UsageTime);
            
        } catch (ParseException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Calculate Bill
        double Amount, Dmd_Charge, Vat, Service_Charge, Principal_Amount,Principal_Amount_Total, Total_Amount;
        
        if (TotalUnit < 50)
	  	{
	        Amount = TotalUnit * 3.50; 
	  	} 
		else if (TotalUnit <= 75)
	  	{
	  		// For the First Fifty Units Charge = 175 (50 * 3.50)
	  		// Next, we are removing those 50 units from total units
	  		Amount = 175 + ((TotalUnit - 50 ) * 4.00);	
	  	}
	  	else if (TotalUnit <= 200)
	  	{
	  		// First 75 Units charge = 300 (75 * 4.00)
	  		// Next, we are removing those 75 units from total units
	  		Amount = 300 + ((TotalUnit - 75 ) * 5.45);
	  	}
		else if (TotalUnit <= 300)
	  	{
	  		// First 75 Units charge = 300 (75 * 4.00) and 200 - 75 is 681.28
	  		// Next, we are removing those 200 units from total units
	  		Amount = 300 + 681.25 +((TotalUnit - 200 ) * 5.70);	
	  	}
		else if (TotalUnit <= 400)
	  	{
	  		// First 75 Units charge = 300 (75 * 4.00), 200 - 75 is 681.28 and 300 - 200 is 570 
	  		// Next, we are removing those 300 units from total units
	  		Amount = 300 + 681.25 + 570 +((TotalUnit - 300 ) * 6.02);
	  	}
		else if (TotalUnit <= 600)
	  	{
	  		// First 75 Units charge = 300 (75 * 4.00), 200 - 75 is 681.28, 300 - 200 is 570 and 400 - 300 in 602
	  		// Next, we are removing those 400 units from total units
	  		Amount = 300 + 681.25 + 570+ 602 +((TotalUnit - 400 ) * 9.30);
	  	}
	  	else
	  	{
	  		// First 75 Units charge = 300 (75 * 4.00), 200 - 75 is 681.28, 300 - 200 is 570, 400 - 300 is 602 and 600 - 400 is 1860
	  		//Next, we are removing those 600 units from total units */ 
			Amount = 300 + 681.25 + 570+ 602 + 1860 +((TotalUnit - 600 ) * 10.70);
		}
		
	Dmd_Charge = 25;
	Principal_Amount = Amount + Dmd_Charge;
	Vat = Principal_Amount * 0.05;
	Service_Charge = Principal_Amount * 0.01;
        
        Principal_Amount_Total = Principal_Amount + Service_Charge;
		
	Total_Amount = Principal_Amount + Vat + Service_Charge;
        
        //Convert To String
        String NetAmmount = String.valueOf(new DecimalFormat("##.##").format(Amount));
        String DemandCharge = String.valueOf(Dmd_Charge);
        String ServiceCharge = String.valueOf(new DecimalFormat("##.##").format(Service_Charge));
        String PrincipalAmmount = String.valueOf(new DecimalFormat("##.##").format(Principal_Amount_Total));
        String VatAmmount = String.valueOf(new DecimalFormat("##.##").format(Vat));
        String TotalBill = String.valueOf(new DecimalFormat("##.##").format(Total_Amount));
        
        //Show Error Input
        if(TotalUnit > 0 && UseTime > 0){
            //Display Data
            TotalUnitShow.setText(TotalUnitOut);
            NetEcectricBill.setText(NetAmmount);
            DemandChargeShow.setText(DemandCharge);
            ServiceChargeShow.setText(ServiceCharge);
            PrincipalAmmountShow.setText(PrincipalAmmount);
            VatAmmountShow.setText(VatAmmount);
            TotalBillShow.setText(TotalBill);
            
            //Hide or Show Panel
            CalculatedDataShow.setVisible(true);
            WrongInput.setVisible(false);
        }
        else{
            WrongInput.setVisible(true);
            CalculatedDataShow.setVisible(false);
        }
        
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CalculatedDataShow.setVisible(false);
        LastReading.setText("Enter Reading");
        CurrentReading.setText("Enter Reading");
        LastDateChooser.setCalendar(null);
        CurrentDateChooser.setCalendar(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LastReadingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastReadingMouseClicked
        // TODO add your handling code here:
        String Temp = LastReading.getText();
        if("Enter Reading".equals(Temp)){
            LastReading.setText(null);
        }
    }//GEN-LAST:event_LastReadingMouseClicked

    private void CurrentReadingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrentReadingMouseClicked
        // TODO add your handling code here:
        String Temp = CurrentReading.getText();
        if("Enter Reading".equals(Temp)){
        CurrentReading.setText(null);
        }
    }//GEN-LAST:event_CurrentReadingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                CalculatedDataShow.setVisible(false);
                WrongInput.setVisible(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private static javax.swing.JPanel CalculatedDataShow;
    private com.toedter.calendar.JDateChooser CurrentDateChooser;
    private javax.swing.JTextField CurrentReading;
    private javax.swing.JLabel DemandChargeShow;
    private com.toedter.calendar.JDateChooser LastDateChooser;
    private javax.swing.JTextField LastReading;
    private javax.swing.JLabel NetEcectricBill;
    private javax.swing.JLabel PrincipalAmmountShow;
    private javax.swing.JLabel ServiceChargeShow;
    private javax.swing.JLabel TotalBillShow;
    private javax.swing.JLabel TotalUnitShow;
    private javax.swing.JLabel UseTimes;
    private javax.swing.JLabel VatAmmountShow;
    private static javax.swing.JPanel WrongInput;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
